---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: istio-broken
  namespace: infra
  labels:
    istio.io/rev: v120
spec:
  hosts:
    - pro-partner.pro.svc.cluster.local
  http:
    - name: "pro-partner-bookings-data-v3"
      match:
        - method:
            exact: 'GET'
          uri:
            regex: '^\/api\/bookings\/v3\/[a-zA-Z0-9-]+$'
