{{- if and .Values.istio.enabled .Values.istio.sidecar }}
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: {{ include "tlsmonitor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tlsmonitor.name" . }}
    helm.sh/chart: {{ include "tlsmonitor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ .Release.Name }}
    {{- include "datadog.labels" . | nindent 4 }}
    {{- include "istio.labels" . | nindent 4 }}
spec:
{{- if .Values.hosts }}
  egress:
  - hosts:
{{- range .Values.hosts }}
{{- range .target }}
    - './{{ . }}'
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.metrics.enabled }}
  ingress:
  - defaultEndpoint: '127.0.0.1:{{ .Values.metrics.port }}'
    port:
      name: http-prom
      number: {{ .Values.metrics.port }}
      protocol: HTTP
{{- end }}
  outboundTrafficPolicy:
    mode: {{ .Values.istio.outboundTrafficPolicy }}
  workloadSelector:
    labels:
      app: {{ .Release.Name }}
{{- end }}
